Map Gererator
VelandelStudio/ProjetJeuVideo pull request #10
Opened 2017-09-04 15:36 UTC by Veltouille

Here are the prefabs and the scripts to generate a map.

The validate Choice is the MapGenerator script during the meeting.

I add a scene for random generation tests.

2017-09-04 21:55 UTC, Myrilandel requested changes

2017-09-04 21:55 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
Est-ce que l'access modifier de rooms est nécessairement Public ? 
Est-ce qu'on pourrait pas passer avec un SerializedField private + Getter/Setter ?

2017-09-04 21:55 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
> +
Est-ce qu'on peut utiliser une structure de type : 
if(. . .) 
   return(Instantiante (. . .) as Transform);

if(. . .) 
   return(Instantiante (. . .) as Transform);

J'ai aucune idée de ce qui serait le mieux en terme de performance, faudrait tester !

2017-09-04 21:55 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
On risque d'utiliser beaucoup de méthodes de types random de ce genre. 
Est-ce que tu penses qu'on pourrait créer une classe Static genre MathHelper.cs qui contiendrait des méthodes de type
public static int GetRandomInt(int seed) ?
Ca pourrait nous éviter de recoder ce types de méthodes à chaque fois

2017-09-04 21:55 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
Est-ce que cette méthode est public ? Ou est-ce qu'on l'appelle uniquement dans le Start ?

2017-09-04 21:56 UTC, Myrilandel commented
Hello j'ai fait une première review ! J'ai fait une Change Request mais en fait c'est plus des questions/réponses car je ne sais pas si ce a quoi j'ai pensé pourrait marcher ! 
En tout cas super boulot 💯 !!

2017-09-05 13:17 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
Oui je pense que tu as raison. On peut faire comme ça.

J'ai mis les fields en public pour pouvoir les testés directement dans l'éditeur ! Mais je pense qu'un clic sur le mécanisme doit créer un dj avec des champs aléatoire.

2017-09-05 13:20 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
Ah mon avis je l'ai faite comme ça de base pour la testé facilement. Cf comm du dessus.

Mais le but c'est de construire un test objet. Donc peut être ajouter un constructeur a cette classe pour instancier un MapGenerator et ensuite call la méthode GenerationMAp.

2017-09-05 13:21 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
Ouais carrément ^^

2017-09-05 13:22 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
> +
Moi non plus à tester !

Je sais que ce n'est pas hyper beau en écriture :/

2017-09-05 13:23 UTC, Veltouille commented
Merci Bulu je m'en charge dès que j'ai le temps.

J'ai bougé la tuile pour que tu puisses mettre les tiennes en pré-prod.

A plus tard

2017-09-05 14:02 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
Ok Ok pour ton info, il existe une modificateur [SerializeField] que tu places devant les fields 
Exemple : [SerializeField] private int i; 
Ca te permet d'afficher dans l'éditeur une variable autre que public :)

2017-09-05 14:04 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
Je propose qu'on laisse comme ça pour l'instant et qu'on crée 2 tuiles sur le KB :  
1 Tuile pour la création de la classe static
1 Tuile pour modifier ce script une fois que la classe static aura été crée

2017-09-05 14:04 UTC, Myrilandel commented
No soucis, j'ai ajouté quelques commentaires aux review du dessus dis moi si tu es OK :)

2017-09-05 14:05 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
> +
En terme d'écriture je pense pas qu'on puisse beaucoup améliorer ça dans tous les cas. C'est surtout pour voir si ça apporte qqch en terme de performance

2017-09-05 14:06 UTC, Myrilandel commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
Le constructeur peut-être une bonne idée ! 
Dis moi si tu trouves des idées de ce côté là

2017-09-05 14:12 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
Je l'avais oublié ^^

Merci Bulu !

2017-09-05 14:14 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
> +     **/
Ça marche, on fait comme ça !

2017-09-05 14:15 UTC, Veltouille commented on Assets/Scripts/Generator/MapGenerator.cs
> +
Ok, dans tout les cas j'étais obliger de travailler chaque cas de la manière que j'ai écris.
Sinon il ne trouve aucun cas de figure et ne sais pas quoi faire.

2017-09-05 14:18 UTC, Veltouille commented
De nada Bro.

Je vais travailler de ce pas sur les autres modifs dont tu m'as parlé.

Juste comme ça rien à voir mais c'est normal que la tuile passe en mode invisible quand on la déplace en terminée ?

2017-09-05 14:22 UTC, Myrilandel commented
Oui j'ai modifié les conditions, quand une tuile passe en terminé elle est cloturée, mais toujours visible si tu désactives les filtres de recherches ("status :")

2017-09-05 15:08 UTC, Myrilandel approved these changes

2017-09-05 15:09 UTC, Myrilandel commented
Ok pour moi niveau code, 
Je teste la branche sur mon Unity ce soir et si no bug je valide la pull request

2017-09-05 15:10 UTC, Veltouille commented
Ca roule ! Merci bulutoo

2017-09-05 19:37 UTC, Myrilandel commented
Tout est OK pour moi, je merge.

2017-09-05 19:37 UTC, merged

2017-09-06 06:41 UTC, Shuko83 commented
Je vois en chaine vos mails,
je ne suis toujours pas dispo pour le code mais je suis de tout coeur avec vous, je suis censé être beaucoup plus dispo à partir de lundi. On se voit jeudi de toute façon.

en tout cas beau boulot et belle motivation

kiss

Fabien

> Le 5 sept. 2017 à 16:06, Myrilandel <notifications@github.com> a écrit :
> 
> @Myrilandel commented on this pull request.
> 
> In Assets/Scripts/Generator/MapGenerator.cs <https://github.com/VelandelStudio/ProjetJeuVideo/pull/10#discussion_r136997566>:
> 
> > @@ -17,10 +26,15 @@ private void Start()
>          GenerationMap();
>      }
>  
> +    /** generation map Method
> +     *  the idea is to place the rooms
> +     **/
> Le constructeur peut-être une bonne idée !
> Dis moi si tu trouves des idées de ce côté là
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub <https://github.com/VelandelStudio/ProjetJeuVideo/pull/10#discussion_r136997566>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AYTSZFxYzWG9BzN23Zd3XvJJDZ9yGOyvks5sfVVpgaJpZM4PMDqL>.
>

2017-09-06 06:44 UTC, Myrilandel commented
Pas de soucis Fab, tu nous avais prévenu ;)
Et oui on fait le point Jeudi, même heure, même endroit !
Force et honneur pour votre oral mes amis !


Le 6 septembre 2017 à 08:41, Shuko83 <notifications@github.com> a écrit :

> Je vois en chaine vos mails,
> je ne suis toujours pas dispo pour le code mais je suis de tout coeur avec
> vous, je suis censé être beaucoup plus dispo à partir de lundi. On se voit
> jeudi de toute façon.
>
> en tout cas beau boulot et belle motivation
>
> kiss
>
> Fabien
>
> > Le 5 sept. 2017 à 16:06, Myrilandel <notifications@github.com> a écrit :
> >
> > @Myrilandel commented on this pull request.
> >
> > In Assets/Scripts/Generator/MapGenerator.cs <https://github.com/
> VelandelStudio/ProjetJeuVideo/pull/10#discussion_r136997566>:
> >
> > > @@ -17,10 +26,15 @@ private void Start()
> > GenerationMap();
> > }
> >
> > + /** generation map Method
> > + * the idea is to place the rooms
> > + **/
> > Le constructeur peut-être une bonne idée !
> > Dis moi si tu trouves des idées de ce côté là
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub <https://github.com/
> VelandelStudio/ProjetJeuVideo/pull/10#discussion_r136997566>, or mute the
> thread <https://github.com/notifications/unsubscribe-auth/
> AYTSZFxYzWG9BzN23Zd3XvJJDZ9yGOyvks5sfVVpgaJpZM4PMDqL>.
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VelandelStudio/ProjetJeuVideo/pull/10#issuecomment-327390068>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQNzLwJEQ1JmBv-ZdRFThKcc2OUsPgyyks5sfj6MgaJpZM4PMDqL>
> .
>

2017-09-06 07:53 UTC, Veltouille commented
Pas de soucis, je vous avez mis tout les deux en reviewer, d'où le spam mail ^^. Bon courage Fab
 
Ju
 
 
 
 
> Message du 06/09/17 08:41
> De : "Shuko83" 
> A : "VelandelStudio/ProjetJeuVideo" 

> Copie à : "Veltouille" , "Author" 
> Objet : Re: [VelandelStudio/ProjetJeuVideo] Map Gererator (#10)
> 
> Je vois en chaine vos mails,
> je ne suis toujours pas dispo pour le code mais je suis de tout coeur avec vous, je suis censé être beaucoup plus dispo à partir de lundi. On se voit jeudi de toute façon.
> 
> en tout cas beau boulot et belle motivation
> 
> kiss
> 
> Fabien
> 
> > Le 5 sept. 2017 à 16:06, Myrilandel  a écrit :
> > 
> > @Myrilandel commented on this pull request.
> > 
> > In Assets/Scripts/Generator/MapGenerator.cs :
> > 
> > > @@ -17,10 +26,15 @@ private void Start()
> > GenerationMap();
> > }
> > 
> > + /** generation map Method
> > + * the idea is to place the rooms
> > + **/
> > Le constructeur peut-être une bonne idée !
> > Dis moi si tu trouves des idées de ce côté là
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub , or mute the thread .
> > 
> 
>
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/VelandelStudio/ProjetJeuVideo","title":"VelandelStudio/ProjetJeuVideo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/VelandelStudio/ProjetJeuVideo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Shuko83 in #10: Je vois en chaine vos mails,\nje ne suis toujours pas dispo pour le code mais je suis de tout coeur avec vous, je suis censé être beaucoup plus dispo à partir de lundi. On se voit jeudi de toute façon.\n\nen tout cas beau boulot et belle motivation\n\nkiss\n\nFabien\n\n\u003e Le 5 sept. 2017 à 16:06, Myrilandel \u003cnotifications@github.com\u003e a écrit :\n\u003e \n\u003e @Myrilandel commented on this pull request.\n\u003e \n\u003e In Assets/Scripts/Generator/MapGenerator.cs \u003chttps://github.com/VelandelStudio/ProjetJeuVideo/pull/10#discussion_r136997566\u003e:\n\u003e \n\u003e \u003e @@ -17,10 +26,15 @@ private void Start()\n\u003e GenerationMap();\n\u003e }\n\u003e \n\u003e + /** generation map Method\n\u003e + * the idea is to place the rooms\n\u003e + **/\n\u003e Le constructeur peut-être une bonne idée !\n\u003e Dis moi si tu trouves des idées de ce côté là\n\u003e \n\u003e —\n\u003e You are receiving this because you were assigned.\n\u003e Reply to this email directly, view it on GitHub \u003chttps://github.com/VelandelStudio/ProjetJeuVideo/pull/10#discussion_r136997566\u003e, or mute the thread \u003chttps://github.com/notifications/unsubscribe-auth/AYTSZFxYzWG9BzN23Zd3XvJJDZ9yGOyvks5sfVVpgaJpZM4PMDqL\u003e.\n\u003e \n\n"}],"action":{"name":"View Pull Request","url":"https://github.com/VelandelStudio/ProjetJeuVideo/pull/10#issuecomment-327390068"}}}