RegenHPSystem in EntityLivingBase, StaticPosHelper and OriginPoint in GameObjectDetector
VelandelStudio/ProjetJeuVideo pull request #21
Opened 2017-10-02 12:46 UTC by Myrilandel

## New Features
**StaticPosHelper**
- This class allows us to get some important positions in the game.
- Works with the GameObjectDetector to get the origin point of the RayCast in front of the player.

## Enhancement
**EntityLivingBase**
- Now has a IsDead bool to ensure that no operations can be done on the entity once it is dead.
- Now has a full Regen HP System. This System is very basic and should be enhanced in the future.

## Bug Fix
**EntityLivingBase**
- Now correctly applies death animation on rigidbody and colliders when an entity dies

## KB Tasks & PlantUML
- [KB Task #68](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=66&project_id=68)
- [KB Task #69](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=66&project_id=69)
- [KB Task #79](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=66&project_id=79)

2017-10-02 12:49 UTC, Myrilandel commented
Hello, toujours dans le but d'alléger ma branche de toutes ses modifications, petites pull request sur le systeme de RegenHP et sur la classe static PosHelper qui permet de récupérer le point d'origine du GameObjectDetector pour lancer toutes sortes de boules de feu devant le joueur pour la suite :D

2017-10-02 16:02 UTC, Veltouille reviewed
Voilà, là aussi j'ai posé quelques questions, donc rien de méchant. Tu as encore fait un super boulot j'ai pas grand chose à dire non plus. J'attends tes réponses pour approuver.

Le code est clair. On se retrouve ce soir pour discuter =)

Beau boulot :+1:

2017-10-02 16:02 UTC, Veltouille commented on Assets/Scripts/Utils/PosHelper.cs
> +}
Je mets juste un commentaire sur cette classe qui pourrait après quelques réflexions, devenir extrêmement utile si nous voulons instancier des donjons asymétriques (ni carré, ni rectangulaire).

A réfléchir pour plus tard.

2017-10-02 16:02 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	private float tick = 0;
Une question concernant tick : ici si je comprends bien, il s'agit d'un tick créé pour refléter le temps de régen PV.

Ma question est donc : si une classe à Dots frappe cette cible, tu utilises les classes de sorts de Dots pour ticker sur la cible ? Ou c'est la cible qui calcul est applique les dégâts en fonction de ses Dots présents sur elle ?

2017-10-02 16:02 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	}
Peu être quelque chose que je n'ai pas compris.

Si il vit : il regen.
Si il meurt tu as fait une pseudo anim dans le code qui "enterre" la cible ?

2017-10-02 16:02 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
>      }
Et là, la Coroutine qui annonce la mort d'une entitée.

Si j'ai bien compris c'est du génie ce que tu as fait xD
Même si à terme je pense qu'il serait bon d'animé les personnage avec des animator.
Je pense que ça évite de créer des booleens et que ca facilité le code.

Cela dit on est pas graphiste et par conséquent je valide se choix. Peut être à voir pour plus tard tranquillement.

2017-10-02 18:50 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	private float tick = 0;
Chaque DoT applique son propre tick. Je pense que ça s'aligne avec le concept "un objet, une action". Pour moi, le systeme de HP ne gère que sa propre regen HP. Par contre, le DoT va appeler la méthode DamageFor() à chacun de ses propres ticks.

2017-10-02 18:51 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	}
Exactement !

2017-10-02 18:52 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
>      }
Merci beaucoup xD 
En fait je suis parti du postulat suivant : Une fois l'animation de mort terminé qu'est-ce qu'on fait du GameObject ? Je me suis rappelé que dans un des tutos de Unity ils faisaient cela donc je l'ai replis (le shooter en vue 3D Ortho).

2017-10-02 18:55 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	private float tick = 0;
Parfait !

Merci pour ta réponse.

2017-10-02 18:57 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
>      }
OK no sweat.

Après si on connais la durée d'une anim, on peut probablement faire un wait attendant que l'anim se termine pour détruire le gameObject.

Mais on pourra faire ça plus tard ;)

2017-10-02 18:58 UTC, Veltouille approved these changes
Là aussi c'est bon pour moi.

Tu as fait encore un sacré taff. :+1:

2017-10-02 19:07 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
>      }
Si je dis pas de connerie, il existe une méthode qui dit "Attend la fin de l'animation pour lancer la suite du code"

2017-10-02 19:07 UTC, Myrilandel commented
Merci beaucoup :)

2017-10-04 06:44 UTC, Myrilandel commented
J'ai modifié la méthode Update en virtual pour qu'on puisse l'override dans les fils

2017-10-04 15:45 UTC, Shuko83 requested changes
La aussi un petit détail à toi de voir ce que tu préfères, mais dans la globalité je ne suis pas trop fan des variables pour enregistrer des booléens. En C# les propriétés simplifies le truc grandement à mon gout :)

2017-10-04 15:45 UTC, Shuko83 commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	private bool IsDead;
Je n'aurais pas sauvegarder la variable mais j'aurais plutôt utilisé une propriété. private bool IsDead{get {return HP>0;}}

2017-10-04 15:45 UTC, Shuko83 commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +		if(!IsDead) {
Si tu utilise la propriété, tu peux aussi t'amuser de créer un public bool IsAlive {get { return !IsDead;}} juste pour simplifier la lecture mais c'est un gros détail

2017-10-04 15:52 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +	private bool IsDead;
Bonne remarque je switch ça dès que possible.

2017-10-04 15:53 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +		if(!IsDead) {
Ben tu sais que je suis un peu maniaque donc effectivement si on peut augmenter la lisibilité je prends x) 
Merci pour la remarque je change ca des que possible.

2017-10-05 16:53 UTC, Myrilandel commented
J'ai apporté les changement @Shuko83 , si tu peux reviewer vite fait pour me donner ou non ton approbation !

2017-10-07 16:20 UTC, merged