Classes, Spells and AutoAttacks Model
VelandelStudio/ProjetJeuVideo pull request #22
Opened 2017-10-02 21:03 UTC by Myrilandel

## New Features
**Classe**
- Adding the Classe System in the game.
- The Classe system is the base of all classes in the game.
- It is built from auto-attack, passive and spells scripts.
- It is able to detect inputs and launch spells correctly.
- Every classes in the game should extend this script.

**Spell**
- Adding the spell System in the game.
- This class is used to know which spell is in use and if a spell is on colldown.
- Every spell on the game should extend this class.

**AutoAttackBase**
- Adding the Auto-Attack base.
- This class handle the behaviour of every auto-attacks of the game.
- This class also handle the GCD of the auto-attacks.

## KB Tasks & PlantUML
- Just insert the Task ID after the "#" and in the link, after "task_id=".
- [KB Task #72](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=72&project_id=3)
- [UML](http://www.plantuml.com/plantuml/uml/dLLDRnen43tZNs4f5z1gJpqILKasJOAK1XJIz3piJbYtnaQsbmP5_UyTUvVzX3JA1PWtu-StN-R2EZ2ks4W6A-iCf8wd4gpbYVz4_iOYWeLQyyl2wKld8FqTN0-mmIcBxeLr_BmC-Shj5gMitNRApah_qkELswCDrnNG9L2RvDi9qWEIxxJ8-DAhu-D93_wnpS3X46zu1wvxA5IQ1o5ZeLofPQOoV9smk3piA8jLuR1XUT8XcV4Xv0vK9l7RQufR9xGAH3XXVnahY_OJZ17QlB4phdT8lpDivJ6US7RMnTk2USFp7TPuakHTZa3IQsL8ckXUf0PNMidrz60dXJ6eN426jG-QZzIUP4GdwpiPzSxCLN2KCPZv75PQIpwpRHnM4aFV_95hORSIzi7_e5qxHAz-OLfrCCZhnoS68VId4zcKDyd1hF5GbkD5Zhfm9xs6wKOOl08fAwxebiP-NbxgSgF_UBsq9Gd11dWQlXOa4msXJmQKVT5cmsMPdQcHAHkn-17sALXt9npFXPkoEDGi1tkZ2vKHlD0qW8G_qttQVE7EfzK63EpdHgo58cn1UObKud9l7MxujZ9f7UDZgcUANWQLalfF5gWtXDsLhwVnTZY97XgnqV5fF36Cl1gevfQPVKJ8zeCvxJmHTHyRj5dX3wNzFxfgap_5LJt1vt5yU5ZQa6S-s34rENTnL2uth-0u-e1PMzq6iJBMNzJQbXRQcNpMUz1zmA2axmU5T2vGPVHVz0y0)
- Please note that the UML will evolve soon, the link will be modified.

_NB : Please note that Warrior and FireMage stands here as exemple. Please DO NOT ADD THESE SCRIPT ON THE PLAYER. At the moment, there are no spells, passive and auto-attacks associated, that will make your game crash._

2017-10-05 14:36 UTC, Myrilandel commented
Hello tout le monde, 
Si ça ne vous ennuie pas j'aimerai que vous attendiez encore un peu avant de review cette pull request. 
Un nouveau commit va arriver pour remettre en conformité (C# rules) l'ensemble des scripts.
La modification arrivera d'ici un ou deux jours max.

2017-10-06 17:22 UTC, Myrilandel commented
Modification OK vous pouvez reviewer si vous voulez :)

2017-10-09 12:17 UTC, Veltouille reviewed
Ok je pense avoir bien compris comment fonctionne la création d'une classe.

Quelques petites question comme d'hab et quelques commentaires. Et si je comprends les réponses je valide

En tout cas ce modèle semble être facile à prendre en main pour la création de classes de personnage. Beau boulot !

2017-10-09 12:17 UTC, Veltouille commented on Assets/Scripts/Classes/Classe.cs
> +public abstract class Classe : MonoBehaviour
On a discuter a propos de cela.

Soit on laisse Classe à la française xD
Soit on l'appel Character, car au final on joue "Le mage feu", "Le Guerrier" etc ;)

2017-10-09 12:17 UTC, Veltouille commented on Assets/Scripts/Classes/Classe.cs
> +    {
J'ai une question sur la méthode.

Type.GetType(PassiveClassName.ToString());

La méthode retourne un objet du type de ce que as entré en string ?
Cela recherche un tel object dasn les ressources (assets) ?

2017-10-09 12:17 UTC, Veltouille commented on Assets/Scripts/AutoAttacks/AutoAttackBase.cs
> +        {
T'as fait un CD qui va de zéro à max OK pas de soucis.

D'habitude on va un timer qui arrive zéro et dit ton sort est up.

C'est pas génant ça marche dans les deux sens !

2017-10-09 12:17 UTC, Veltouille commented on Assets/Scripts/Spells/Spell.cs
> +    protected void DisplaySpellNotLauncheable(Spell spell)
Bonne idée =)

2017-10-09 12:21 UTC, Myrilandel commented on Assets/Scripts/Classes/Classe.cs
> +    {
Exactement, en gros je lui dis, trouve moi un script qui porte le nom donné dans PassiveClassName

2017-10-09 12:22 UTC, Myrilandel commented on Assets/Scripts/AutoAttacks/AutoAttackBase.cs
> +        {
C'est une bonne remarque au contraire, je vais le changer car quand on fera le GUI si on voudra afficher le temps de recharge restant on devrait se frapper des calculs pour rien. 
Modification dans le prochaine commit.

2017-10-09 12:23 UTC, Myrilandel commented on Assets/Scripts/Spells/Spell.cs
> +    protected void DisplaySpellNotLauncheable(Spell spell)
Merci !

2017-10-09 12:24 UTC, Myrilandel commented on Assets/Scripts/Classes/Classe.cs
> +public abstract class Classe : MonoBehaviour
On en avait deja parlé, ce sera modifié dans le prochain commit vers Character ;)

2017-10-09 12:26 UTC, Myrilandel commented
Merci pour tes commentaires, j'espère avoir été clair dans mes réponses.
Peux-tu marquer ta request comme Changes requested stp ?
Histoire de ne pas merge avant que j'ai apporté les modifications 
Merci ! :)

2017-10-09 12:52 UTC, Veltouille commented on Assets/Scripts/Classes/Classe.cs
> +public abstract class Classe : MonoBehaviour
Parfait =)

2017-10-09 12:52 UTC, Veltouille commented on Assets/Scripts/Classes/Classe.cs
> +    {
C'est forcément un script ?

2017-10-09 12:53 UTC, Veltouille commented on Assets/Scripts/AutoAttacks/AutoAttackBase.cs
> +        {
Okay ca marche pour moi !

2017-10-09 12:54 UTC, Veltouille commented
J'ai juste demandé si ça va forcément chercher un script dans le GetType .... Mais tu peux merge Je suis Ok

2017-10-09 12:54 UTC, Veltouille approved these changes

2017-10-09 13:01 UTC, Myrilandel commented on Assets/Scripts/Classes/Classe.cs
> +    {
Oui

2017-10-09 13:03 UTC, Myrilandel commented
Non justement je voulais pas que tu approuves je dois changer des trucs comme je t'ai dit dans les commentaires xD

2017-10-09 13:04 UTC, Veltouille commented on Assets/Scripts/Classes/Classe.cs
> +    {
Okay, plus que parfait alors !

2017-10-09 13:05 UTC, Veltouille requested changes
Pardon j'ai pas vu le message xD

2017-10-09 13:08 UTC, Myrilandel commented
Pas de soucis haha

2017-10-09 13:22 UTC, Myrilandel commented on Assets/Scripts/Classes/Classe.cs
> +    {
Il est question de conjugaison ?

2017-10-09 13:27 UTC, Veltouille commented on Assets/Scripts/Classes/Classe.cs
> +    {
xD

2017-10-09 16:39 UTC, Myrilandel commented on Assets/Scripts/AutoAttacks/AutoAttackBase.cs
> +        {
Okay donc ces éléments seront repris dans un enhancement sur les Spells/AutoAttacks quand on s'occupera des GUI, je pense que le mieux serait d'attendre d'ici là étant donné qu'on est sur tout les fronts en ce moment et que toutes ces classes vont subir une refacto dans le lot 2 dont je t'avais parlé.

2017-10-09 16:44 UTC, Myrilandel commented
Modification OK pour chanement du nom de CLasse => Character.
La modification de tout ce qui concerne les CD fera parti d'un Enhancement dans le prochain lot.

2017-10-09 16:45 UTC, Veltouille approved these changes

2017-10-09 16:45 UTC, merged