GUI Spells, New CD Rotation and GUI Description on spells.
VelandelStudio/ProjetJeuVideo pull request #38
Opened 2017-11-10 17:47 UTC by Myrilandel

## New Features
**GUISpellDisplayer**
- Script associated to the SpellBarPrefab.
- One instance of this script is used for each spell.
- This script allows to display all informations you need to know about a spell ingame. 
- Adding Cooldown informations.
- Adding Description while the cursor is over the spell.
- Adding images per spell.
- Adding Layer to know if a spell is launchable or not in special conditions.
- insert a "-" for each element you want to talk about.

## Enhancement
**Character**
- Now able to find an instance of GUISpellDisplayer and associates a spell to it.

**Spell**
- Now has a description field.
- Now has an abstract method used by inherited classes to fill the description field.
- All inherited scripts has been modified in order to fit with the new abstract method.
- Now has a new cooldown rotation (the spell is ready when the CurrentCD reaches 0).

## KB Tasks & PlantUML
- [KB Task #137](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=137&project_id=3)
- [KB Task #138](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=138&project_id=3)
- [KB Task #139](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=139&project_id=3)
- [KB Task #141](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=141&project_id=3)
- [KB Task #143](https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=143&project_id=3)

2017-11-13 07:49 UTC, Myrilandel commented
Je viens de m'apercevoir que j'ai zappé certaines méthodes au niveau des commentaires, je les ajoute dans une prochain commit aujourd'hui !

2017-11-14 17:51 UTC, Myrilandel commented
J'ai ajouté de nouveaux éléments notamment la construction des spells directement depuis un JSON. Ça fait beaucoup d'éléments nouveaux à prendre en main hésitez pas à vous envoyer sur les questions !

2017-11-16 08:47 UTC, Veltouille commented
Je commence ma review et déjà l'UML est excellent avec le Model et la description de l'utilisation du JSON.

2017-11-16 09:16 UTC, Myrilandel commented
Merci j'ai essayé d'être le plus clair possible car le mécanisme n'est pas évident.
tu noteras que j'ai représenté le JSON au format de class Enum mais c'est bel et bien un fichier .JSON (j'avais pas trop le choix pour le représenter).

2017-11-16 10:09 UTC, Veltouille reviewed
Voila je te laisse une bonne série de commets =)

Sinon c'est un sacré truc que tu as pondu là. Toujours admiratif du boulot que tu fais =D

Je te dit merde aussi pour mon travail sur la migration que tu as encore modifié, mais bon ça a heureusement du sens alors j'approuve.

Super boulot Jo, réponds au questions et remarques et je validerai =) :+1:

2017-11-16 10:09 UTC, Veltouille commented on Assets/StreamingAssets/SpellData.json
> +]
### Question

Ok, donc c'est le JSON qui décrit les sorts d'un champion.
Je vois que seul le FireMage est renseigné, ma question c'est est que ce JSON remplace l'ancien CharacterData.json ou les deux sont nécessaires à la création d'un champion ?

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/Utils/StringHelper.cs
> +                    description = description.Replace("{" + matches[i].Value + "}", "<b><color=" + color + ">{" + matches[i].Value.TrimStart('m') + "}</color></b>");
### Question

J'ai compris que tu fais sauter le 'm' quand tu match sur le pattern et quand tu change la couleur par rapport au type de spell. Mais tu fais sauté le 'p' aussi ?

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/Utils/StringHelper.cs
> +        pattern = @"(?<=<<).*?(?=>>)";
### Question

Il faudra que tu m'explique comment et sur quoi tu t'es basé pour faire ton pattern. S'il te plait xD

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/Utils/StringHelper.cs
> +}
### Remarque

J'ai compris à quoi sert la classe. C'est un super travail que tu as fait pour cette static.

Cependant (et parce que je suis chiant), les méthodes de la classes ne sont pas commentées. Je pense que ça pourrait aider parce que c'est pas évident au premier abord. De plus, je pense que tu utilises des codes que tu as fait par toi même et je pense de manière arbitraire (si je ne dit pas de bêtises ^^). Il serait bien de les explicités pour que les autres puisses au plus facilement construire leur propres spells.

Sinon c'est propre :+1:

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/GUI/GUISpellDisplayer.cs
> +        spellImage.sprite = Resources.Load<Sprite>("Images/Spells/" + _spell.GetComponent<Character>().GetType().ToString() + "/" + _spell.GetType());
### Question

Spell.GetType() te donne le nom du spell ?

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/GUI/GUISpellDisplayer.cs
> +        _timerCDText.text = ((int)_spell.currentCD + 1).ToString();
### Question

_timerCDText.text c'est le petit texte qui est en bas à droite de l'icone de spell.
Mais je ne comprends pas le +1

??? xD

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/Classes/BASE_CHARS/Spell.cs
> +}
Je pense avoir répondu à ma question sur les JSON : Il faut les deux !

L'un pour charger le champion, l'autre pour charger les spells.

Sinon j'ai pas de question sur cette classe, tout est clair.

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/Classes/BASE_CHARS/Character.cs
> +        for (int i = 1; i <= 4; i++)
### Question 

AttributeSpellToGUI(spellToAdd, i); ne peut pas prendre la valeur 0 ?

2017-11-16 10:09 UTC, Veltouille commented on Assets/Scripts/Classes/BASE_CHARS/Character.cs
>  }
### Remarque

A part peut être une petite explication sur indexSpell de la méthode AttributeSpellToGUI(Spell spell, int indexSpell).
Je ne vois pas pourquoi il faut que cela commence à 1.

Sinon Nickel t'es toujours un champion =)

2017-11-16 10:16 UTC, Myrilandel commented on Assets/Scripts/Classes/BASE_CHARS/Character.cs
> +        for (int i = 1; i <= 4; i++)
Il le peut c'est simplement que sur le GUI le premier prefab qui accueille le spell s'appelle Spell1 
Du coup faudrait modifier le prefab si on veut le changer.

2017-11-16 10:17 UTC, Myrilandel commented on Assets/Scripts/Classes/BASE_CHARS/Character.cs
>  }
Merci ;)

2017-11-16 10:18 UTC, Myrilandel commented on Assets/Scripts/Classes/BASE_CHARS/Spell.cs
> +}
Exact à terme, on devrait avoir 
1 Json Pour champion, 1 pour Spells, 1 pour les Autoattacks, 1 pour les passifs et 1 pour le status

2017-11-16 10:19 UTC, Veltouille commented on Assets/Scripts/Classes/BASE_CHARS/Spell.cs
> +}
Logique Ok !

2017-11-16 10:20 UTC, Myrilandel commented on Assets/Scripts/GUI/GUISpellDisplayer.cs
> +        _timerCDText.text = ((int)_spell.currentCD + 1).ToString();
Oui c'est ça en fait le +1 est pour une simple question de rendu et d'arrondis. 
Exemple, si mon spell à un CD de 3 sec, au premier tick il passera a 2.98 sec. A l'arrondi à l'écran, on verra 2, puis 1 , puis 0.
Le fait d'ajouter +1 permettra de rendre à l'écran 3 puis 2 puis 1. les deux choix se valent on parlera du rendu ce soir pendant le weekly si tu veux.

2017-11-16 10:21 UTC, Myrilandel commented on Assets/Scripts/GUI/GUISpellDisplayer.cs
> +        spellImage.sprite = Resources.Load<Sprite>("Images/Spells/" + _spell.GetComponent<Character>().GetType().ToString() + "/" + _spell.GetType());
Exact, faut juste lui accoler un ToString pour s'en servir

2017-11-16 10:22 UTC, Myrilandel commented on Assets/Scripts/Utils/StringHelper.cs
> +                    description = description.Replace("{" + matches[i].Value + "}", "<b><color=" + color + ">{" + matches[i].Value.TrimStart('m') + "}</color></b>");
C'est une erreur effectivement j'ai fais une refacto hier soir sur ce script et j'ai pas testé avec un P
Bien vu ! je corrige ca ce soir en vitesse

2017-11-16 10:22 UTC, Veltouille commented on Assets/Scripts/GUI/GUISpellDisplayer.cs
> +        _timerCDText.text = ((int)_spell.currentCD + 1).ToString();
T'es un génie !

2017-11-16 10:25 UTC, Veltouille commented on Assets/Scripts/Utils/StringHelper.cs
> +                    description = description.Replace("{" + matches[i].Value + "}", "<b><color=" + color + ">{" + matches[i].Value.TrimStart('m') + "}</color></b>");
;)

2017-11-16 10:26 UTC, Myrilandel commented on Assets/Scripts/Utils/StringHelper.cs
> +        pattern = @"(?<=<<).*?(?=>>)";
C'est une sorte de printf amélioré. 
{p0} = La première valeur de la chaîne sera un dégât physique (Gras + Maron).
{m1} = La seconde valeur de la chaîne sera une dégat magique (Gras + Cyan).
{2} = La troisième valeur est une variable ni physique ni magique (Gras).
<<MonTexte>> = Le texte entre <<>> doit représenter le nom d'un autre script à description. (Gras + Vert + Ajoute une sous-section de description) 
Ce sera une façon de dire, j'ajoute (par exemple) <<IgniteStatus>> dans mon text, donc forcément, en dessous de ma description principale, j'ajouterai la description de l'IgniteStatus

2017-11-16 10:27 UTC, Myrilandel commented on Assets/Scripts/Utils/StringHelper.cs
> +}
Effectivement j'ai zappé les comments de cette méthode alors qu'ils sont absolument nécessaires pour construire une bonne chaîne. Sera ajouté dans le commit de ce soir :)

2017-11-16 10:27 UTC, Veltouille commented on Assets/Scripts/Utils/StringHelper.cs
> +        pattern = @"(?<=<<).*?(?=>>)";
Cela me paraissait important de l'expliciter !

2017-11-16 10:28 UTC, Myrilandel commented on Assets/StreamingAssets/SpellData.json
> +]
Il faut garder les deux (C.F. Mon commentaires précédent)

2017-11-16 10:28 UTC, Veltouille commented on Assets/StreamingAssets/SpellData.json
> +]
Je sais, j'ai reviewé par le bas mdr !

2017-11-16 10:29 UTC, Veltouille commented
Ok suite à tes réponses je laisse la PR en request changes pour le commit de ce soir ;)

2017-11-16 10:30 UTC, Myrilandel commented
Merci pour tous tes commentaires, il y a effectivement des erreurs qu'on ne peut pas laisser partir en prod si tu peux me laisser la PR en request changes stp :) 

Merci beaucoup !

2017-11-16 10:30 UTC, Veltouille requested changes
Pour le Commit de ce soir, pour verrouiller en attendant !

2017-11-16 17:24 UTC, Myrilandel commented on Assets/Scripts/GUI/GUISpellDisplayer.cs
> +        _timerCDText.text = ((int)_spell.currentCD + 1).ToString();
Merci ! :D

2017-11-16 17:57 UTC, Veltouille approved these changes
Un bug fixe de qualité sur ta PR je ne peux que validé ^^

2017-11-16 18:04 UTC, Veltouille commented
Aller PR terminée, je merge =)

Super travail Jo, ça va être génial :+1:

2017-11-16 18:04 UTC, merged