Windiator creationclass And HotFixes
VelandelStudio/ProjetJeuVideo pull request #47
Opened 2018-01-14 13:25 UTC by Veltouille

2018-01-15 08:04 UTC, Myrilandel commented
Belle PR avec pleins de tasks :D Je commence la review d'ici peu.
J'aimerai qu'on fixe le bug du double chargement de spells avant de merge car c'est un problème qu'on ne rencontrait pas avant ([https://velandelstudio.com/kanboard/?controller=TaskViewController&action=show&task_id=211&project_id=3](url))

2018-01-16 09:10 UTC, Myrilandel requested changes
Un très très gros sprint qui s'achève avec un énorme travail.
Beaucoup de refacto et du nouveaux éléments, la PR parle d'elle même. Tu as fais un travail monstre sur le champion et tous les bugFixes associés. On a vraiment quelque chose de clair, et d'optimisé pour la suite donc gros GG. 
J'ai laissé quelques commentaires tu verras qu'il n'y a que très peu de choses à changer (la plupart du temps des commentaires/nom de variables).
Je passe en Request Changes le temps d'avoir mes réponses. Encore gg pour le boulot accompli ;)

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/BASE_CHAMPION/Spell.cs
> -    public int NumberOfStacks;
Je me demande si on devrait pas rapatrier les StackableSpells directement dans les spells.
Faire une fusion des deux classes et avoir une détection d'un bool IsStackable depuis un JSON.
Ca éviterai de devoir décider de mettre a chaque fois un extends Spell ou StackableSpell (on limite les erreurs et on se prend pas le choux)
Qu'est-ce que tu en penses ?

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/MeleAttack.cs
> +    protected void OnTriggerEnter(Collider other)
Je ne comprends pas pourquoi cette méthode n'est ni virtual ni abstract ? 
Est-ce que c'est volontaire ?

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/MeleAttack.cs
> +    public bool GetValueColArme()
Est-ce que tu penses qu'on pourrait remplacer cette méthode Get par une propriété get{}; set{} ?
Je sais qu'elles sont moins gourmandes

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/Windiator/AutoAttack/AutoAttackWindiator.cs
> +    private WindiatorSimpleAttack _wsa;
Je chipote mais je suis pas trop fan des noms de variable acronymes :D . A l'occase est-ce qu'on pourra mettre un 
_windiatorSimpleAttack ?

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/Windiator/AutoAttack/AutoAttackWindiator.cs
> +            _anim.SetTrigger("AutoAttack");
Bien ouej ;)

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/GustStatus.cs
> +
Bien qu'elle soit vide, est-ce qu'on pourrait mettre des commentaires dans cette classe stp ? 
Ainsi qu'un debug.Log pour qu'on sache à terme ce que devrai faire ce Status. Ca nous évitera d'aller fouiner dans toutes les archi pour retrouver son but

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/StormWallBehaviour.cs
> +        Invoke("DestroyItself", float.Parse(_parentSpell.OtherValues[1]));
L'invoke est une très bonne idée, on avait vu ensemble je me souviens.
Je m'étais renseigné par la suite et voilà ce que j'ai pu tirer de la doc. 
Les invokes sont très coûteuses mais sont très intéressantes parce qu'on peut les canceler. Par exemple Je pose un status avec un Invoke d'une methode qui me détruira ce Status au bout de x secondes. Si on reset le status alors on a just a CancelInvoke et reInvoke dans x secondes.

Dans notre cas, je pense qu'on pourrait simplement mettre un Destroy(GameObject obj, float time). A moins que tu comptes ajouter une mécanique qui puisse annuler la destruction du mur ? 
Qu'en penses tu ?

2018-01-16 09:10 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +        if (gameObject.tag != "Player")
J'ai pas prêté attention et je me suis trompé sur cette partie, j'ai mis tous les Debug.Log en français :D 
Je corrigerai quand on passera sur Sentinelle

2018-01-16 12:20 UTC, Veltouille commented on Assets/Scripts/Champions/Windiator/AutoAttack/AutoAttackWindiator.cs
> +            _anim.SetTrigger("AutoAttack");
lol merci !

2018-01-16 12:21 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
> +        if (gameObject.tag != "Player")
Ok pas de soucis !

2018-01-16 12:35 UTC, Veltouille reviewed
J'ai répondu, je vais certaines modif ce soir !

2018-01-16 12:35 UTC, Veltouille commented on Assets/Scripts/Champions/BASE_CHAMPION/Spell.cs
> -    public int NumberOfStacks;
Je pense que ça peut faire une classe plus chargée mais que ça peut être pratique pour la suite =)

2018-01-16 12:35 UTC, Veltouille commented on Assets/Scripts/Champions/MeleAttack.cs
> +    protected void OnTriggerEnter(Collider other)
Je ne sais pas si tu te souviens mais j'avais un soucis en lançant le test qui me disait que je ne pouvait déclarer ma classe comme abstract. Donc, je l'ai corrigé pour que cela fonctionne.

A tester de nouveau mais avec l’apparition d'un véritable model, je ne sais pas comment ça va s'agencer.

Pour répondre à ta question, pour le moment c'est volontaire.

2018-01-16 12:35 UTC, Veltouille commented on Assets/Scripts/Champions/MeleAttack.cs
> +    public bool GetValueColArme()
Je ne sais pas, pour moi c'est facile à tester si tu veux faire un :

         if (!_wsa.GetValueColArme())
         {
             _wsa.SwapEnableArmeCol();
         }

Mais si c'est possible avec un "get set" je n'ai juste pas eu l'idée donc pourquoi pas =)

2018-01-16 12:35 UTC, Veltouille commented on Assets/Scripts/Champions/Windiator/AutoAttack/AutoAttackWindiator.cs
> +    private WindiatorSimpleAttack _wsa;
Selon votre bon vouloir, Messire Buluto !

2018-01-16 12:35 UTC, Veltouille commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/StormWallBehaviour.cs
> +        Invoke("DestroyItself", float.Parse(_parentSpell.OtherValues[1]));
> Dans notre cas, je pense qu'on pourrait simplement mettre un Destroy(GameObject obj, float time). A moins que tu comptes ajouter une mécanique qui puisse annuler la destruction du mur ?
Qu'en penses tu ?

Maintenant que tu en parles pourquoi pas ajouter certaines méca, mais pas maintenant. Donc soit on a un PC méga puissant soit on change avec la solution du Destroy(GameObject obj, float time) ?

2018-01-16 12:42 UTC, Veltouille reviewed
Ta partie !

2018-01-16 12:42 UTC, Veltouille commented on Assets/Scripts/Entities/EntityLivingBase.cs
>      }
Super les tests de correction d'entity et de son rigidbody =)
A mettre en Anglais pour enfoncer le clou ^^

D'ailleurs et sauf erreur de ma part j'ai pas vu de "Rigidbite" MDR.

2018-01-16 12:49 UTC, Myrilandel commented on Assets/Scripts/Champions/MeleAttack.cs
> +    protected void OnTriggerEnter(Collider other)
Okay ca marche en fait ce que je trouve bizarre c'est que tu puisses la déclarer sans Virtual et que tu la redefinisse dans les classes filles sans messages d'avertissement. On regardera plus tard c'est pas gênant pour le moment !

2018-01-16 12:50 UTC, Myrilandel commented on Assets/Scripts/Champions/MeleAttack.cs
> +    public bool GetValueColArme()
Le test sera identique normalement

2018-01-16 12:52 UTC, Myrilandel commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/StormWallBehaviour.cs
> +        Invoke("DestroyItself", float.Parse(_parentSpell.OtherValues[1]));
L'idée c'est de se dire quel est le meilleur outil? 
Un Invoke permet de lancer une méthode dans X secondes avec possibilité de cancel ce lancement, c'est gourmand.
Un Destroy au bout de x seconde ne peut pas se cancel mais c'est moins gourmand. Les deux sont viables mais comme je te disais l'autre fois, si on économise 1% de CPU ici, on peut utiliser 1% de plus sur une mécanique plus interessante :)

2018-01-16 12:53 UTC, Veltouille commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/GustStatus.cs
> +
Vu que c'est toi qui à fait le Gust mdr !

2018-01-16 12:53 UTC, Myrilandel commented on Assets/Scripts/Entities/EntityLivingBase.cs
>      }
Je n'ai pas osé :D

2018-01-16 13:24 UTC, Veltouille commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/StormWallBehaviour.cs
> +        Invoke("DestroyItself", float.Parse(_parentSpell.OtherValues[1]));
Donc je peux changer la méthode pour le moment, on verra plus tard !

2018-01-16 13:47 UTC, Myrilandel commented on Assets/Scripts/Champions/Windiator/ScriptsOnPrefabs/StormWallBehaviour.cs
> +        Invoke("DestroyItself", float.Parse(_parentSpell.OtherValues[1]));
Ca roule !

2018-01-16 19:27 UTC, Veltouille commented
Voilà, j'ai fait les derniers changes : 

J'ai modifié la variable `_wsa;`
j'ai passé une variable `public Bool colArme { get; set; }`
J'ai changé l'Invoke par un Destroy.

Merci pour ta review, merci pour avoir bosser avec moi sur mes tâches, c'était vraiment plus intéressant,
et merci pour ton message pour la PR ça fait vraiment plaisir !

On va cartonner la suite du PJV !
Tu peux merger quand tu veux.

2018-01-16 20:03 UTC, Myrilandel approved these changes

2018-01-16 20:03 UTC, merged